---
abstract: 'Processing PYX data or file and write as SGML via Tags.'
author:
  - 'Michal Josef Spacek <skim@cpan.org>'
build_requires:
  English: 0
  Error::Pure::Utils: 0.15
  ExtUtils::MakeMaker: 6.36
  File::Object: 0.07
  Tags::Output::Indent: 0.09
  Tags::Output::Raw: 0.13
  Test::More: 0
  Test::NoWarnings: 0
  Unicode::UTF8: 0
configure_requires:
  ExtUtils::MakeMaker: 6.36
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.21'
license: bsd
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: PYX-SGML-Tags
no_index:
  directory:
    - examples
    - inc
    - t
    - xt
requires:
  Class::Utils: 0.05
  Error::Pure: 0.15
  PYX::Parser: 0.08
  PYX::Utils: 0.01
  Tags::Output::Raw: 0.11
  perl: 5.6.2
resources:
  bugtracker: https://github.com/michal-josef-spacek/PYX-SGML-Tags/issues
  homepage: https://github.com/michal-josef-spacek/PYX-SGML-Tags
  license: http://opensource.org/licenses/bsd-license.php
  repository: git://github.com/michal-josef-spacek/PYX-SGML-Tags
version: '0.11'
